version: '3.8'
services:

  nginx:
    image: nginx:alpine
    ports:
      - 8001:80
    volumes:
      - .:/app
      - ./configs/dev/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./configs/dev/nginx/nginx.conf:/etc/nginx/nginx.conf
