# Generated by Django 5.0.4 on 2024-04-25 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admission_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Admissão'),
        ),
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição do Dev'),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Dev'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Gênero do Dev'),
        ),
        migrations.AddField(
            model_name='user',
            name='github',
            field=models.URLField(blank=True, null=True, verbose_name='Github do Dev'),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='Linkedin do Dev'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefone do Dev'),
        ),
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='home/images/devs', verbose_name='Imagem do Dev'),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo do Dev'),
        ),
        migrations.AddField(
            model_name='user',
            name='resignation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Saída'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo do Dev'),
        ),
        migrations.AddField(
            model_name='user',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.unit', verbose_name='Unidade'),
        ),
    ]
