# Generated by Django 5.0.4 on 2024-04-25 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_admission_date_user_birthdate_user_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='boss',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Chefe'),
        ),
    ]
