# Generated by Django 5.0.4 on 2024-04-25 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento do Dev'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome Completo do Dev'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, null=True, verbose_name='Gênero do Dev'),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome preferencial do Dev'),
        ),
    ]
