# Generated by Django 5.0.4 on 2024-04-25 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_birthdate_alter_user_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome Preferencial do Dev'),
        ),
    ]
