# Generated by Django 5.0.4 on 2024-04-24 19:59

import django.core.validators
import django.db.models.deletion
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Dev')),
                ('board', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo do Dev')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição do Dev')),
                ('image', models.ImageField(blank=True, null=True, upload_to='home/images/devs', verbose_name='Imagem do Dev')),
            ],
            options={
                'verbose_name': 'Dev',
                'verbose_name_plural': 'Devs',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us_text', models.TextField(blank=True, null=True, verbose_name='Texto Sobre a V3L0Z')),
                ('about_us_image', models.ImageField(blank=True, null=True, upload_to='home/images/logos', verbose_name='Imagem da Seção Sobre a V3L0Z')),
                ('projects_text', models.TextField(blank=True, null=True, verbose_name='Texto da Seção de Projetos')),
                ('how_works_text', models.TextField(blank=True, null=True, verbose_name='Texto da Seção de Como Funciona')),
                ('navbar_brand', models.FileField(blank=True, null=True, upload_to='home/images/logos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'webp', 'gif']), home.models.validate_file_size], verbose_name='Logo da Navbar')),
                ('navbar_brand_alt', models.CharField(blank=True, max_length=100, null=True, verbose_name='Texto Alternativo da Logo da Navbar')),
                ('footer_brand', models.FileField(blank=True, null=True, upload_to='home/images/logos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'webp', 'gif']), home.models.validate_file_size], verbose_name='Logo do Rodapé')),
                ('promotional_video', models.FileField(blank=True, null=True, upload_to='home/videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'm4v']), home.models.validate_file_size], verbose_name='Vídeo Promocional')),
                ('video_thumbnail', models.ImageField(blank=True, null=True, upload_to='home/videos/thumb', verbose_name='Thumbnail do Vídeo Promocional')),
                ('index_description', models.TextField(blank=True, null=True, verbose_name='Descrição do Site')),
                ('metatags_image', models.ImageField(blank=True, null=True, upload_to='home/images/logos', verbose_name='Imagem do Site')),
            ],
            options={
                'verbose_name': 'Configuração',
                'verbose_name_plural': 'Configurações',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_network', models.CharField(choices=[('alexa', 'Alexa'), ('behance', 'Behance'), ('discord', 'Discord'), ('dribbble', 'Dribbble'), ('facebook', 'Facebook'), ('github', 'Github'), ('gitlab', 'Gitlab'), ('google', 'Google'), ('instagram', 'Instagram'), ('line', 'Line'), ('linkedin', 'Linkedin'), ('mastodon', 'Mastodon'), ('medium', 'Medium'), ('messenger', 'Messenger'), ('microsoft-teams', 'Microsoft Teams'), ('opencollective', 'Opencollective'), ('paypal', 'Paypal'), ('pinterest', 'Pinterest'), ('quora', 'Quora'), ('reddit', 'Reddit'), ('signal', 'Signal'), ('sina-weibo', 'Sina Weibo'), ('skype', 'Skype'), ('slack', 'Slack'), ('snapchat', 'Snapchat'), ('sourceforge', 'Sourceforge'), ('spotify', 'Spotify'), ('stack-overflow', 'Stack Overflow'), ('strava', 'Strava'), ('substack', 'Substack'), ('telegram', 'Telegram'), ('tencent-qq', 'Tencent QQ'), ('threads', 'Threads'), ('threads-fill', 'Threads Fill'), ('tiktok', 'Tiktok'), ('twitch', 'Twitch'), ('twitter', 'Twitter'), ('twitter-x', 'Twitter X'), ('vimeo', 'Vimeo'), ('wechat', 'Wechat'), ('whatsapp', 'Whatsapp'), ('wordpress', 'Wordpress'), ('yelp', 'Yelp'), ('youtube', 'Youtube'), ('link', 'Outra')], max_length=100, verbose_name='Rede Social')),
                ('link', models.URLField(verbose_name='Link da Rede Social')),
                ('is_main', models.BooleanField(default=False, verbose_name='Principal')),
                ('dev', models.ForeignKey(blank=True, help_text='Deixe em branco para adicionar rede social como da própria Academia V3L0Z.', null=True, on_delete=django.db.models.deletion.CASCADE, to='home.dev', verbose_name='Desenvolvedor')),
            ],
            options={
                'verbose_name': 'Rede Social',
                'verbose_name_plural': 'Redes Sociais',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Unidade')),
                ('local', models.CharField(blank=True, max_length=100, null=True, verbose_name='Localização da Unidade')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição da Unidade')),
                ('image', models.ImageField(blank=True, null=True, upload_to='home/images/units', verbose_name='Imagem da Unidade')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link da Unidade')),
                ('devs', models.ManyToManyField(blank=True, to='home.dev', verbose_name='Desenvolvedores')),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Projeto')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição do Projeto')),
                ('image', models.ImageField(blank=True, null=True, upload_to='home/images', verbose_name='Imagem do Projeto')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link do Projeto')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.unit', verbose_name='Unidade')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
            },
        ),
    ]
