# Generated by Django 5.0 on 2023-12-22 20:52

import django.core.validators
import django.db.models.deletion
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Dev')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição do Dev')),
                ('image', models.ImageField(blank=True, null=True, upload_to='home/images/devs', verbose_name='Imagem do Dev')),
            ],
            options={
                'verbose_name': 'Dev',
                'verbose_name_plural': 'Devs',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Projeto')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição do Projeto')),
                ('image', models.ImageField(blank=True, null=True, upload_to='home/images', verbose_name='Imagem do Projeto')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link do Projeto')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us_text', models.TextField(blank=True, null=True, verbose_name='Texto Sobre a V3L0Z')),
                ('projects_text', models.TextField(blank=True, null=True, verbose_name='Texto da Seção de Projetos')),
                ('how_works_text', models.TextField(blank=True, null=True, verbose_name='Texto da Seção de Como Funciona')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='home/images', verbose_name='Logo')),
                ('promotional_video', models.FileField(blank=True, null=True, upload_to='home/videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov']), home.models.validate_file_size], verbose_name='Vídeo Promocional')),
                ('video_thumbnail', models.ImageField(blank=True, null=True, upload_to='home/videos/thumb', verbose_name='Thumbnail do Vídeo Promocional')),
            ],
            options={
                'verbose_name': 'Configuração',
                'verbose_name_plural': 'Configurações',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_network', models.CharField(max_length=100, verbose_name='Rede Social')),
                ('link', models.URLField(verbose_name='Link da Rede Social')),
                ('dev', models.ForeignKey(blank=True, help_text='Deixe em branco para adicionar rede social como da própria Academia V3L0Z.', null=True, on_delete=django.db.models.deletion.CASCADE, to='home.dev', verbose_name='Desenvolvedor')),
            ],
            options={
                'verbose_name': 'Rede Social',
                'verbose_name_plural': 'Redes Sociais',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Unidade')),
                ('local', models.CharField(blank=True, max_length=100, null=True, verbose_name='Localização da Unidade')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição da Unidade')),
                ('image', models.ImageField(blank=True, null=True, upload_to='home/images/units', verbose_name='Imagem da Unidade')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link da Unidade')),
                ('devs', models.ManyToManyField(blank=True, to='home.dev', verbose_name='Desenvolvedores')),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
            },
        ),
    ]
