# Generated by Django 5.0 on 2023-12-23 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='logo',
        ),
        migrations.AddField(
            model_name='setting',
            name='about_us_image',
            field=models.ImageField(blank=True, null=True, upload_to='home/images/logos', verbose_name='Imagem da Seção Sobre a V3L0Z'),
        ),
        migrations.AddField(
            model_name='setting',
            name='footer_brand',
            field=models.ImageField(blank=True, null=True, upload_to='home/images/logos', verbose_name='Logo do Rodapé'),
        ),
        migrations.AddField(
            model_name='setting',
            name='index_description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição do Site'),
        ),
        migrations.AddField(
            model_name='setting',
            name='metatags_image',
            field=models.ImageField(blank=True, null=True, upload_to='home/images/logos', verbose_name='Imagem do Site'),
        ),
        migrations.AddField(
            model_name='setting',
            name='navbar_brand',
            field=models.ImageField(blank=True, null=True, upload_to='home/images/logos', verbose_name='Logo'),
        ),
    ]
