# Generated by Django 5.0.4 on 2024-04-25 22:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_unit_devs_remove_socialmedia_dev_delete_dev_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='devs',
            field=models.ManyToManyField(blank=True, related_name='units', to=settings.AUTH_USER_MODEL, verbose_name='Desenvolvedores'),
        ),
    ]
