# Generated by Django 5.0 on 2023-12-23 03:33

import django.core.validators
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_setting_logo_setting_about_us_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dev',
            name='board',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo do Dev'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='promotional_video',
            field=models.FileField(blank=True, null=True, upload_to='home/videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'm4v']), home.models.validate_file_size], verbose_name='Vídeo Promocional'),
        ),
    ]
