# Generated by Django 5.0 on 2023-12-23 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_dev_board_alter_setting_promotional_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Principal'),
        ),
    ]
