# Generated by Django 5.0 on 2023-12-23 04:12

import django.core.validators
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_setting_navbar_brand_alt_alter_setting_navbar_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='footer_brand',
            field=models.FileField(blank=True, null=True, upload_to='home/images/logos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'webp', 'gif']), home.models.validate_file_size], verbose_name='Logo do Rodapé'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='navbar_brand',
            field=models.FileField(blank=True, null=True, upload_to='home/images/logos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'webp', 'gif']), home.models.validate_file_size], verbose_name='Logo da Navbar'),
        ),
    ]
