# Generated by Django 5.0 on 2023-12-23 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_setting_footer_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.unit', verbose_name='Unidade'),
        ),
    ]
